<?php

namespace ContainerO16tRFs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MBdfj7tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mBdfj7t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mBdfj7t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'competences' => ['privates', 'App\\Repository\\CompetencesRepository', 'getCompetencesRepositoryService', true],
            'sites' => ['privates', '.errored.BTTnR6d', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::index()": the $sites argument is type-hinted with the non-existent class or interface: "App\\Controller\\SitesRepository". Did you forget to add a use statement?'],
            'timeline' => ['privates', '.errored.SLxNfcD', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::index()": the $timeline argument is type-hinted with the non-existent class or interface: "App\\Controller\\TimelineRepository". Did you forget to add a use statement?'],
        ], [
            'competences' => 'App\\Repository\\CompetencesRepository',
            'sites' => '?',
            'timeline' => '?',
        ]);
    }
}
