<?php

namespace ContainerO16tRFs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RVfveGBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RVfveGB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RVfveGB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'timelineRepository' => ['privates', 'App\\Repository\\TimelineRepository', 'getTimelineRepositoryService', true],
        ], [
            'timelineRepository' => 'App\\Repository\\TimelineRepository',
        ]);
    }
}
