<?php

namespace ContainerO16tRFs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IvWkHiYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ivWkHiY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ivWkHiY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sitesRepository' => ['privates', 'App\\Repository\\SitesRepository', 'getSitesRepositoryService', true],
        ], [
            'sitesRepository' => 'App\\Repository\\SitesRepository',
        ]);
    }
}
