<?php

namespace ContainerO16tRFs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IfxSfuAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IfxSfuA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IfxSfuA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'timeline' => ['privates', '.errored..service_locator.IfxSfuA.App\\Entity\\Timeline', NULL, 'Cannot autowire service ".service_locator.IfxSfuA": it references class "App\\Entity\\Timeline" but no such service exists.'],
        ], [
            'timeline' => 'App\\Entity\\Timeline',
        ]);
    }
}
