<?php

namespace ContainerO16tRFs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSitesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Vd2yWgt.App\Entity\Sites' shared service.
     *
     * @return \App\Entity\Sites
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Vd2yWgt": it references class "App\\Entity\\Sites" but no such service exists.');
    }
}
