<?php

namespace ContainerO16tRFs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimelineTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TimelineType' shared autowired service.
     *
     * @return \App\Form\TimelineType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TimelineType.php';

        return $container->privates['App\\Form\\TimelineType'] = new \App\Form\TimelineType();
    }
}
