<?php

namespace ContainerO16tRFs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimelineService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IfxSfuA.App\Entity\Timeline' shared service.
     *
     * @return \App\Entity\Timeline
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.IfxSfuA": it references class "App\\Entity\\Timeline" but no such service exists.');
    }
}
