<?php

namespace ContainerD37ogqT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3xd3WboService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3xd3Wbo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3xd3Wbo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'competences' => ['privates', 'App\\Repository\\CompetencesRepository', 'getCompetencesRepositoryService', true],
            'sites' => ['privates', 'App\\Repository\\SitesRepository', 'getSitesRepositoryService', true],
            'timeline' => ['privates', 'App\\Repository\\TimelineRepository', 'getTimelineRepositoryService', true],
        ], [
            'competences' => 'App\\Repository\\CompetencesRepository',
            'sites' => 'App\\Repository\\SitesRepository',
            'timeline' => 'App\\Repository\\TimelineRepository',
        ]);
    }
}
