<?php

namespace ContainerD37ogqT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T7tlpz9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t7tlpz9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t7tlpz9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CompetencesController::delete' => ['privates', '.service_locator.kvkaJ38', 'get_ServiceLocator_KvkaJ38Service', true],
            'App\\Controller\\CompetencesController::edit' => ['privates', '.service_locator.kvkaJ38', 'get_ServiceLocator_KvkaJ38Service', true],
            'App\\Controller\\CompetencesController::index' => ['privates', '.service_locator.43ajRrC', 'get_ServiceLocator_43ajRrCService', true],
            'App\\Controller\\CompetencesController::show' => ['privates', '.service_locator.kvkaJ38', 'get_ServiceLocator_KvkaJ38Service', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.3xd3Wbo', 'get_ServiceLocator_3xd3WboService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SitesController::delete' => ['privates', '.service_locator.Vd2yWgt', 'get_ServiceLocator_Vd2yWgtService', true],
            'App\\Controller\\SitesController::edit' => ['privates', '.service_locator.Vd2yWgt', 'get_ServiceLocator_Vd2yWgtService', true],
            'App\\Controller\\SitesController::index' => ['privates', '.service_locator.ivWkHiY', 'get_ServiceLocator_IvWkHiYService', true],
            'App\\Controller\\SitesController::new' => ['privates', '.service_locator.fZXk27d', 'get_ServiceLocator_FZXk27dService', true],
            'App\\Controller\\SitesController::show' => ['privates', '.service_locator.Vd2yWgt', 'get_ServiceLocator_Vd2yWgtService', true],
            'App\\Controller\\TimelineController::delete' => ['privates', '.service_locator.IfxSfuA', 'get_ServiceLocator_IfxSfuAService', true],
            'App\\Controller\\TimelineController::edit' => ['privates', '.service_locator.IfxSfuA', 'get_ServiceLocator_IfxSfuAService', true],
            'App\\Controller\\TimelineController::index' => ['privates', '.service_locator.RVfveGB', 'get_ServiceLocator_RVfveGBService', true],
            'App\\Controller\\TimelineController::show' => ['privates', '.service_locator.IfxSfuA', 'get_ServiceLocator_IfxSfuAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CompetencesController:delete' => ['privates', '.service_locator.kvkaJ38', 'get_ServiceLocator_KvkaJ38Service', true],
            'App\\Controller\\CompetencesController:edit' => ['privates', '.service_locator.kvkaJ38', 'get_ServiceLocator_KvkaJ38Service', true],
            'App\\Controller\\CompetencesController:index' => ['privates', '.service_locator.43ajRrC', 'get_ServiceLocator_43ajRrCService', true],
            'App\\Controller\\CompetencesController:show' => ['privates', '.service_locator.kvkaJ38', 'get_ServiceLocator_KvkaJ38Service', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.3xd3Wbo', 'get_ServiceLocator_3xd3WboService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SitesController:delete' => ['privates', '.service_locator.Vd2yWgt', 'get_ServiceLocator_Vd2yWgtService', true],
            'App\\Controller\\SitesController:edit' => ['privates', '.service_locator.Vd2yWgt', 'get_ServiceLocator_Vd2yWgtService', true],
            'App\\Controller\\SitesController:index' => ['privates', '.service_locator.ivWkHiY', 'get_ServiceLocator_IvWkHiYService', true],
            'App\\Controller\\SitesController:new' => ['privates', '.service_locator.fZXk27d', 'get_ServiceLocator_FZXk27dService', true],
            'App\\Controller\\SitesController:show' => ['privates', '.service_locator.Vd2yWgt', 'get_ServiceLocator_Vd2yWgtService', true],
            'App\\Controller\\TimelineController:delete' => ['privates', '.service_locator.IfxSfuA', 'get_ServiceLocator_IfxSfuAService', true],
            'App\\Controller\\TimelineController:edit' => ['privates', '.service_locator.IfxSfuA', 'get_ServiceLocator_IfxSfuAService', true],
            'App\\Controller\\TimelineController:index' => ['privates', '.service_locator.RVfveGB', 'get_ServiceLocator_RVfveGBService', true],
            'App\\Controller\\TimelineController:show' => ['privates', '.service_locator.IfxSfuA', 'get_ServiceLocator_IfxSfuAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CompetencesController::delete' => '?',
            'App\\Controller\\CompetencesController::edit' => '?',
            'App\\Controller\\CompetencesController::index' => '?',
            'App\\Controller\\CompetencesController::show' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SitesController::delete' => '?',
            'App\\Controller\\SitesController::edit' => '?',
            'App\\Controller\\SitesController::index' => '?',
            'App\\Controller\\SitesController::new' => '?',
            'App\\Controller\\SitesController::show' => '?',
            'App\\Controller\\TimelineController::delete' => '?',
            'App\\Controller\\TimelineController::edit' => '?',
            'App\\Controller\\TimelineController::index' => '?',
            'App\\Controller\\TimelineController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CompetencesController:delete' => '?',
            'App\\Controller\\CompetencesController:edit' => '?',
            'App\\Controller\\CompetencesController:index' => '?',
            'App\\Controller\\CompetencesController:show' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SitesController:delete' => '?',
            'App\\Controller\\SitesController:edit' => '?',
            'App\\Controller\\SitesController:index' => '?',
            'App\\Controller\\SitesController:new' => '?',
            'App\\Controller\\SitesController:show' => '?',
            'App\\Controller\\TimelineController:delete' => '?',
            'App\\Controller\\TimelineController:edit' => '?',
            'App\\Controller\\TimelineController:index' => '?',
            'App\\Controller\\TimelineController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
