<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD37ogqT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD37ogqT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD37ogqT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD37ogqT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD37ogqT\App_KernelDevDebugContainer([
    'container.build_hash' => 'D37ogqT',
    'container.build_id' => 'c1ee3ba4',
    'container.build_time' => 1610117893,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD37ogqT');
